### ISSUE TITLE
Organising your repo

### ISSUE THREAD

**Issue by etiennemarais** [mannuelf/php#1]
## Summary

Having a clean repo makes finding things super easy. I would suggest you clean up the files and move them into folders that group them based on the module and the lesson numbers in that module. 

```
/The First Steps
     ... // files
/Data Types and More
     ... // files
```

This would make reading through and understanding your repo quite well

**Comment by mannuelf** [comment]
@etiennemarais repo has been organised :smile:

**Comment by etiennemarais** [comment]
Great work :D
