### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by etiennemarais** [mannuelf/php#3]
### Summary

I'd like you to along with your modules focus on some array work for me.

Small things that you can improve on is the new php uses array shorthands: `[]` instead of `array()` to align more with other languages. https://github.com/manidf/php/blob/master/02_data-types/arrays.php#L16 

### The things

I'd like you to focus on some array work where you solve some problems related to data inside of arrays. I want to chat to you regarding an array problem a week on top of the modules. What do you think?

As a first pass I want you to read the php docs on arrays and the methods available to support you in getting data in and out of arrays. Also how the actual storage of data in arrays work on a memory level and why it's bad to only rely on arrays to store bigger data sets but if they are smaller you can do wondrous things with them. I think we should use this issue as a thread for async questions and progress. 

#### Getting started

- [Arrays](http://php.net/manual/en/language.types.array.php)
- [Array functions](http://php.net/manual/en/ref.array.php)

**Comment by mannuelf** [comment]
cool looking at this today [",][".]

**Comment by mannuelf** [comment]
oh wow check this out:
https://visualgo.net/
https://visualgo.net/en/hashtable?slide=1

**Comment by mannuelf** [comment]
oh i see now "As of PHP 5.4 you can also use the short array syntax, which replaces array() with []"

**Comment by etiennemarais** [comment]
You can start off by taking an rss feed of you choice and parsing that into an array using SimpleXml as a starting point. I'd like you to use your classes knowledge here also.

### Task

Please make an object that takes a rss feed of your choice and adds functionality to it. The feed must be stored on the class as an array and operations must be done on it like searching for an item, listing all items and getting a url out of each item in the feed for example.

You can hard code the config elements for now like rss feed url. Please chat to me about any questions you have :D
